### ISSUE TITLE
Uncaught TypeError: Cannot read property 'css' of null

### ISSUE THREAD

**Issue by nethulap** [itsdrewmiller/angular-perfect-scrollbar#25]
My application is a single page angular app using the angular-perfect-scrollbar. when the app is in mobile mode(app running on mobile emulator) i get this error "Uncaught TypeError: Cannot read property 'css' of null". The error is repeated many times as if its in infinite loop until i refresh the page.

![csserror](https://cloud.githubusercontent.com/assets/7296306/5464170/bb0a3516-85d8-11e4-9b78-af30098ae6f1.png)

The following code is used in many places of the application.
`<div perfect-scrollbar id="scrollid" class="scroller" include-padding="true" always-visible-y="true" refresh-on-change="myArray" style="height: 350px" min-scrollbar-length="25">`

No error when the app is in desktop mode.

Is there a solution for this issue?

**Comment by vapits** [comment]
+1 I've got the same error with or without angular. It works perfectly on browser but on smartphones or even chrome smartphone emulator gives me arror like:

TypeError: Cannot read property 'event' of undefined
    at Object.e.exports [as destroy] (perfect-scrollbar.min.js:2)
    at HTMLDivElement.<anonymous> (perfect-scrollbar.min.js:2)

**Comment by itsdrewmiller** [comment]
You should probably report this error in the perfect scrollbar repository:  http://noraesae.github.io/perfect-scrollbar/

**Comment by jigar029** [comment]
I am also getting same error while using Chrome Emulator. Agreed that this is issue with library. I am using directive right into my code and html template. I haven't installed this library through bower or anything. So, did anyone found solution on this that can directly be applied to directive?

I am new to angular and using this library caused this 'css' of null error. Any help or redirection to correct path will be appreciated. :)
