### ISSUE TITLE
Bower version for Perfect-Scrollbar

### ISSUE THREAD

**Issue by aseckel** [itsdrewmiller/angular-perfect-scrollbar#33]
Seems the perfect-scrollbar library has removed version 0.4.11 that this library depends on from their bower register.

Any chance of an update for this library to support more recent versions of perfect scrollbar?

**Comment by Patrik-Lundqvist** [comment]
Yeah we need a dependency update, it doesn't work with bower currently

**Comment by karlkori** [comment]
Hey, please update version for perfect-scrollbar

**Comment by luisrudge** [comment]
Yeah. I'm having this problem too

**Comment by erezgiga** [comment]
+1

**Comment by clementSabattie** [comment]
Hi, I have the same problem ! 
Please update ! 
thank you in advance

**Comment by veswill3** [comment]
I am guessing you are already aware, but when I tried installing via bower, it asked me if I wanted to use 0.5.9 instead. You can add this to your bower.json file
``` json
"resolutions": {
  "perfect-scrollbar": "~0.5.9"
},
```
It is a decent enough workaround.

**Comment by clementSabattie** [comment]
Hi,

I have tried this and it doesn't work.

this is what i have on my jenkis :

bower perfect-scrollbar#~0.4.11     ENORESTARGET No tag found that was
able to satisfy ~0.4.11

Additional error details:
Available versions: 0.5.9, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3,
0.5.2, 0.5.1, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2,
0.4.1, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1


2015-02-16 21:45 GMT+01:00 Vesper <notifications@github.com>:

> I am guessing you are already aware, but when I tried installing via
> bower, it asked me if I wanted to use 0.5.9 instead. You can add this to
> your bower.json file
>
> "resolutions": {
>   "perfect-scrollbar": "~0.5.9"
> },
>
> It is a decent enough workaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itsdrewmiller/angular-perfect-scrollbar/issues/33#issuecomment-74569849>
> .
>



-- 
-- 

Clément SABATTIÉ
06 87 35 23 16

**Comment by JHernan** [comment]
Hi !

I have the same issue.

bower perfect-scrollbar#~0.4.11                ENORESTARGET No tag found that was able to satisfy ~0.4.11

Additional error details:
Available versions: 0.5.9, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1

Can you fix it?

Thank you in advance !!

**Comment by KapuzenSohn** [comment]
Some issue here.

**Comment by maksad** [comment]
+1

**Comment by forrestLyman** [comment]
I resolved this issue by specifying the latest release (not the actual release #):

"dependencies": {
    "bootstrap": "latest",
    "angular": "latest",
    "angular-bootstrap": "latest",
    "angular-route": "latest",
    "angular-animate": "latest",
    "font-awesome": "latest",
    "perfect-scrollbar": "latest"
  }

**Comment by fxuniverse** [comment]
same here..is there a way to override this thing in the meantime ?

**Comment by maksad** [comment]
@fxuniverse  yes there is. You can folk the package from `https://github.com/itsdrewmiller/angular-perfect-scrollbar` and the go to your own `repositories` make the change right on the github. The change is: ` "perfect-scrollbar": "~0.5.1",` in file `https://github.com/itsdrewmiller/angular-perfect-scrollbar/blob/master/bower.json`
and refer to your forked repository in your own project. like:

`"angular-perfect-scrollbar": "https://github.com/fxuniverse/angular-perfect-scrollbar.git#fbff161155621288d81b6d78890f13c1ff9d88a3"`

**Comment by warpdesign** [comment]
@maksad Thanks but I'm getting this error when trying to install it with bower install as you suggested:
`bower ENOTFOUND Package angular-perfect-scrollbar: not found`

**Comment by maksad** [comment]
@warpdesign . I not sure but probably the link to the `angular-perfect-scrollbar` is not available. Please, make sure to follow these setps and if its still does not work let me know:
1. fork the project at https://github.com/itsdrewmiller/angular-perfect-scrollbar
2. go to your profile and find the project there. eg. : `https://github.com/` + YourUsername (warpdesign) + `/angular-perfect-scrollbar`
3. make the changes: 

![screen shot 2015-02-19 at 15 11 20](https://cloud.githubusercontent.com/assets/4527650/6267080/a43fc780-b849-11e4-8d32-b3f5b9e914b9.png)

4. Commit the changes
5. Copy and pass the link to your `bower.json` file

![screen shot 2015-02-19 at 15 14 15](https://cloud.githubusercontent.com/assets/4527650/6267121/00f91ae4-b84a-11e4-8b09-9006a5b11277.png)
`"angular-perfect-scrollbar": "https://github.com/' + YourUsername (warpdesign) + '/angular-perfect-scrollbar.git"`

6. Copy the latest SHA:

![screen shot 2015-02-19 at 15 12 49](https://cloud.githubusercontent.com/assets/4527650/6267096/d8086158-b849-11e4-8c74-717f072ebb5d.png)

and append it to your link:

`"angular-perfect-scrollbar": "https://github.com/' + YourUsername (warpdesign) + '/angular-perfect-scrollbar.git#23whatEverIsYourSha"`

if it does not work try to get it form my fork like:

`"angular-perfect-scrollbar": "https://github.com/maksad/angular-perfect-scrollbar.git#fbff161155621288d81b6d78890f13c1ff9d88a3"`

or let me know

**Comment by ttbarnes** [comment]
Not ideal by any means, but using the approach @maksad suggests works.

**Comment by orrgal1** [comment]
where is the guy who wrote this? why doesn't he just fix this??

**Comment by joel-nyansa** [comment]
@orrgal1 maybe he's on vacation? :sunglasses:

**Comment by jnfeinstein** [comment]
@orrgal1 maybe he's on vacation? :sunglasses:

**Comment by KapuzenSohn** [comment]
Hey commented a Pull-Request 2 days after this Ticket

**Comment by L3V147H4N** [comment]
I did all the steps, fork, change, commit but still nothing, then I tried using the for from @maksad and I still get the same error :P

**Comment by maksad** [comment]
@L3V147H4N I am not sure what can be the issue in your case, but one of the reason that you still get the same error might be a small 'typo' somewhere in the `bower.json` link. If you don't mind, can you please paste the link here.

**Comment by L3V147H4N** [comment]
Here is the link to the Fork https://github.com/L3V147H4N/angular-perfect-scrollbar#ca8b6ed611da0b5df5dbb5f85d6caf9f4930dba2

**Comment by maksad** [comment]
@L3V147H4N please try to install it manually, and if it installs just include the link bellow into your project `bower.json` file

here is the command:
`bower install https://github.com/maksad/angular-perfect-scrollbar.git#fbff161155621288d81b6d78890f13c1ff9d88a3`

**Comment by L3V147H4N** [comment]
It Worked, but the link wasn't the problem, I didn't noticed that I hadn't deleted the angular-perfect-scrollbar folder from the bower_components folder and it was causing the error. Thank You for your help!

**Comment by minimaldesign** [comment]
Hmmm… Are we to assume that this project is not active anymore?

**Comment by alexmgrant** [comment]
Hey all, I created a fork that fixes the dependency if you'd like to use it within your project for simplicity.   
[cc-angular-perfect-scrollbar](https://github.com/CareerCruising/angular-perfect-scrollbar)  
`bower install cc-angular-perfect-scrollbar --save`

**Comment by itsdrewmiller** [comment]
https://github.com/itsdrewmiller/angular-perfect-scrollbar/releases/tag/v0.0.4
