### ISSUE TITLE
No tag found that was able to satisfy ~0.4.11

### ISSUE THREAD

**Issue by maksad** [itsdrewmiller/angular-perfect-scrollbar#37]
Hi Drew Miller,

Seems that the `perfect-scrollbar#~0.4.11` does not exist anymore. Instead there are another available versions and probably you have to change your `bower.json`

     "dependencies": {
        "perfect-scrollbar": "~0.4.11",
        "angular": "*"
      },

https://github.com/itsdrewmiller/angular-perfect-scrollbar/blob/master/bower.json#L12

while installing I got the following error:

    bower angular-perfect-scrollbar#0.0.3           cached git://github.com/itsdrewmiller/angular-perfect-scrollbar.git#0.0.3
    bower angular-perfect-scrollbar#0.0.3         validate 0.0.3 against git://github.com/itsdrewmiller/angular-perfect-scrollbar.git#0.0.3
    bower perfect-scrollbar#~0.4.11             not-cached git://github.com/noraesae/perfect-scrollbar-bower.git#~0.4.11
    bower perfect-scrollbar#~0.4.11                resolve git://github.com/noraesae/perfect-scrollbar-bower.git#~0.4.11
    bower perfect-scrollbar#~0.4.11           ENORESTARGET No tag found that was able to satisfy ~0.4.11

    Additional error details:
    Available versions: 0.5.9, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1

**Comment by clementSabattie** [comment]
https://github.com/itsdrewmiller/angular-perfect-scrollbar/issues/33

**Comment by vapits** [comment]
+1
I have the same issue and cannot find any way to install it :S

**Comment by maksad** [comment]
@vapits check #33 I posted a way to fix this issue

**Comment by itsdrewmiller** [comment]
https://github.com/itsdrewmiller/angular-perfect-scrollbar/releases/tag/v0.0.4
