### ISSUE TITLE
 ENORESTARGET No tag found that was able to satisfy ~0.4.11

### ISSUE THREAD

**Issue by binhqd** [itsdrewmiller/angular-perfect-scrollbar#41]
Hi,

I used this component before and it run normally. However, I've just encountered this error since this version doesn't exist anymore. I received followings suggestion:

Additional error details:
Available versions: 0.6.1, 0.6.0, 0.5.9, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1

I think you need to modify the bower.json with new version of perfect-scollbar

**Comment by KapuzenSohn** [comment]
Double with #33
Please look if there is a ticket for your Problem and when not create a ticket. In the linked Ticket is also a quick and dirty solution

**Comment by binhqd** [comment]
Thank you.
I'm currently using angular-perfect-scrollbar-4.1.1fixed for my bower.json.
Will check it if the problem solved

**Comment by ws-hofshteyn** [comment]
fix pls 4.1.11 to 4.1.1 
https://github.com/itsdrewmiller/angular-perfect-scrollbar/blob/master/bower.json#L12

**Comment by itsdrewmiller** [comment]
Will do.

**Comment by itsdrewmiller** [comment]
https://github.com/itsdrewmiller/angular-perfect-scrollbar/releases/tag/v0.0.4
