### ISSUE TITLE
Force scroll to bottom?

### ISSUE THREAD

**Issue by jkelleher** [itsdrewmiller/angular-perfect-scrollbar#48]
Wondering how I might have container scroll to show most-recently added item. Have:
`
<perfect-scrollbar id="scrollStudents" style="max-height:130px; overflow-y:hidden;position:relative;" suppress-scroll-x="true" refresh-on-change="selectedStudents" refresh-on-resize="true">
`

Ideas anyone?

**Comment by rayronvictor** [comment]
You can use the attribute `scroll-down` and the `refresh-on-change`.

```html
<perfect-scrollbar scroll-down="true" refresh-on-change="myCollection">
    <div ng-repeat="item in myCollection"> ... </div>
</perfect-scrollbar>
```

**Comment by mukulgupta2507** [comment]
@rayronvictor  works like a charm.Thanks

**Comment by ptitdje45** [comment]
@rayronvictor works like a charm.Thanks

+1 ! Thanks dude !
