### ISSUE TITLE
Scrollbar doesn't appear on first mouse over

### ISSUE THREAD

**Issue by bogdy29** [itsdrewmiller/angular-perfect-scrollbar#5]
Hy

First time when you go with mouse over, the scrollbar is not appearing.

if you start scrolling then will appear and will be ok.

thanks

**Comment by zsajjad** [comment]
@bogdy29 what was the solution?

**Comment by bogdy29** [comment]
I don't remember exactly and I removed it from the app. 

Also I am a big fan of NOT using and touching any scroll bar. We should let the customer/end-user decide what browser he prefer to use. If a scroll bar is ugly in IE, he will use then Chrome or he will 
accept the scrollbar from IE. It's a long discussion, but anyway good luck and I hope you will not have problems with it(including IE performance problems).
