### ISSUE TITLE
$elem.perfectScrollbar is not a function

### ISSUE THREAD

**Issue by capsule5** [itsdrewmiller/angular-perfect-scrollbar#55]
Seems that something goes wrong with the initialization of jquery plugin

**Comment by mcianc** [comment]
implement perfect-scrollbar.with-mousewheel.min.js

**Comment by arm5077** [comment]
Doesn't look like `perfect-scrollbar.with-mousewheel.min.js` is included in perfect-scrollbar's bower install.

**Comment by jazzlikethat** [comment]
Indeed `perfect-scrollbar.with-mousewheel.min.js` is missing in the installation. Any solution for this?

**Comment by atefth** [comment]
This is really stupid that the docs mentions of this .with-mousewheel.min file which is not shipped with bower.

**Comment by johncant** [comment]
Angular bundles its own lightweight JQuery implementation called jqlite. This problem can be fixed by making sure JQuery is loaded before Angular.

**Comment by cyril-blanco** [comment]
In my case, this error is shown because I have no jQuery (and I have not intention to add it just for a scrollbar). The fundamental problem is that this directive only uses the jQuery version of the perfect-scrollbar and does not fallback to the vanilla version when jQuery is not there.

**Comment by TareqElMasri** [comment]
Having the same issue, what's the solution?

**Comment by cyril-blanco** [comment]
@TareqElMasri If you don't include jQuery, the solution is to replace the `$elem.perfectScrollbar()` calls with the vanilla equivalents ([docs on perfect-scrollbar project page](https://github.com/noraesae/perfect-scrollbar)). You might need to change some jQ calls too if not compatible with jQlite (I didn't check details)

**Comment by psoaresbj** [comment]
Any solution for this!??

**Comment by cyril-blanco** [comment]
PR #47 solves this. 
Here's an example of how the main script should read without jQ: https://github.com/CareerCruising/angular-perfect-scrollbar/blob/e27ef2b9fa485dce55b591bfefad8e5260f88460/src/angular-perfect-scrollbar.js

**Comment by brunomperes** [comment]
Any updates? I still get this error on bower latest version

**Comment by isherwood** [comment]
I'm hoping to find a bit more time to look into #47. Haven't gotten there yet.

**Comment by ChintanRaval** [comment]
I'm facing this issue too on the current latest version of [0.1.0](https://github.com/itsdrewmiller/angular-perfect-scrollbar/releases/tag/v0.1.0). However, the issue doesn't exist if I use version [0.0.4](https://github.com/itsdrewmiller/angular-perfect-scrollbar/releases/tag/v0.0.4).

**Comment by kis25791** [comment]
facing same issue as @ChintanRaval. Any solution?

**Comment by cyril-blanco** [comment]
@ChintanRaval, @kis25791: which solution did you try?

**Comment by isherwood** [comment]
Sorry, work has been heavy lately and I haven't found time. Pull requests from v1.1.0 are welcome. 

@kis25791, you can find the files for 0.0.4 in the [Releases list](https://github.com/itsdrewmiller/angular-perfect-scrollbar/releases/tag/v0.0.4).

**Comment by ChintanRaval** [comment]
@cyril-blanco , @kis25791 , I ended up _not_ using this package (with a plain css replacement for the time being, which is not optimal, but does the trick). 

```
.my-scroll-vertical {
  overflow-y: scroll;
  background: linear-gradient(#ffffff 30%, rgba(255, 255, 255, 0)), linear-gradient(rgba(255, 255, 255, 0), #ffffff 70%) 0 100%, radial-gradient(farthest-side at 50% 0, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0)), radial-gradient(farthest-side at 50% 100%, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0)) 0 100%;
  background-repeat: no-repeat;
  background-size: 100% 40px, 100% 40px, 100% 14px, 100% 14px;
  background-attachment: local, local, scroll, scroll;
  background-color: white;
}
.my-scroll-vertical::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}
/* Track */
.my-scroll-vertical::-webkit-scrollbar-track {
  -webkit-box-shadow: inset 0 0 6px rgba(147, 149, 151, 0.5);
  -webkit-border-radius: 10px;
  border-radius: 10px;
}
```

**Comment by matthewbryancurtis** [comment]
I was having some similar issues: didn't want to pull in jQuery and even with jQuery was getting `$elem.perfectScrollbar is not a function` which was preventing perfect-scrollbar from working at all. After some tinkering, I'm working on a solution that seems to be going well.

* It uses perfect-scrollbar v1.3 (latest)
* It doesn't require jQuery to be pulled in
* It changes three lines in angular-perfect-scrollbar

First I added `var ps;` after line 5 to have an easily accessible reference to the PerfectScrollbar object.

On line 46, I changed `$elem.perfectScrollbar(options);` to `ps = new PerfectScrollbar($elem[0], options);` to use the new perfect-scrollbar constructor.

On line 83, I changed `$elem.perfectScrollbar('update');` to `ps.update();` since I believe that's how the new perfect-scrollbar gets updated.

I'm still getting an error regarding lines 49-63 of `angular-perfect-scrollbar`, but it's been awhile since I've worked with jQuery directly so I haven't spent any time rewriting those.

I've created a Glitch to showcase the changes (again, please note the three bullet points above): https://glitch.com/edit/#!/vagabond-passenger

**Comment by TareqElMasri** [comment]
3 years and still counting

**Comment by cyril-blanco** [comment]
@TareqElMasri This is the kind of despicable message that can make someone drop a project. It is open source which means the author is probably coding it on his spare time. He doesn't owe you anything and you did not contribute in any way to solve this problem while other people participating in this discussion came with a solution proposal or rolled their own.

Please don't expect people to do your job.

**Comment by isherwood** [comment]
jQuery has been eliminated as a dependency in #94.
