### ISSUE TITLE
Bower installation steps wrong

### ISSUE THREAD

**Issue by BannedForLife** [itsdrewmiller/angular-perfect-scrollbar#59]
When following the steps to install via bower, I noticed that 
`<script src="bower_components/perfect-scrollbar/min/perfect-scrollbar.with-mousewheel.min.js"></script>`
`<script src="bower_components/angular-perfect-scrollbar/src/angular-perfect-scrollbar.js"></script>`
are not in the bower_components.

**Comment by vjandrei** [comment]
Yep I have the same issue.

**Comment by isherwood** [comment]
Resolved in later versions.
