### ISSUE TITLE
Scroll only is displayed on scroll

### ISSUE THREAD

**Issue by xzegga** [itsdrewmiller/angular-perfect-scrollbar#63]
In library example the scroll is showed on hover or mouseenter, but in my app only is showed when scroll up or down over the div with scroll.

How I can resolve this issue?

**Comment by AliPoder** [comment]
+1

**Comment by bfelda** [comment]
+1

**Comment by islavi** [comment]
This should be fixed in: "angular-perfect-scrollbar.js"

Replace the line in 52:
$elem.bind('mouseenter', update('mouseenter'));

With this line:
$elem.bind('mouseenter', function($event) {update('mouseenter');});

**Comment by AliPoder** [comment]
Horay! Well, thank you. That worked well :) :+1:

**Comment by cgiacomi** [comment]
yeah this works for me as well! :))  :+1:

**Comment by cgiacomi** [comment]
is there a pull request for this???

**Comment by Bled68** [comment]
If you don't want to fork or modify the lib. 
You can add:
`ng-mouseenter="update('mouseenter')"` on your perfect-scrollbar directive.

**Comment by Maximaximum** [comment]
The fix suggested by @islavi works for me as well!

**Comment by isherwood** [comment]
Fixed in later versions.
