### ISSUE TITLE
Replaces ul with div

### ISSUE THREAD

**Issue by tariqporter** [itsdrewmiller/angular-perfect-scrollbar#69]
Element <ul perfect-scrollbar></ul> is replaced with a div, which is incorrect and breaks html.
Whilst it is understandable why this is happening because of the transclusion, it is not mentioned that you shouldn't put this on a ul element

**Comment by isherwood** [comment]
You shouldn't use the directive on any element that doesn't match what's in the template. Best practice is to assume that'll happen.

**Comment by tariqporter** [comment]
In the directive `restrict: 'EA'` is used, which is incorrect, as the E will never work with anything other than `div`. This is not mentioned anywhere.

**Comment by isherwood** [comment]
That's a fair point. I'll look at updating the docs. I'm still getting my head into this repo. 

Thanks.

**Comment by isherwood** [comment]
Attribute option removed for version 0.2.1.
