### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jagged3dge** [itsdrewmiller/angular-perfect-scrollbar#70]
I do not see any activity past the Jan, 2015. There seems to be a plethora of PRs pending merges. If @itsdrewmiller is not interested in maintaining this repo, it'd be best to ask for anyone who'd want to maintain (or atleast co-maintain) this project.

**Comment by itsdrewmiller** [comment]
Yeah I'd love to add a new maintainer here.

Mobile: (515) 451-4509
Fax: Click here

**Comment by isherwood** [comment]
Working on it! :)
