### ISSUE TITLE
I think this is code mistake

### ISSUE THREAD

**Issue by saadshahd** [itsdrewmiller/angular-perfect-scrollbar#73]
[Line at the src](https://github.com/itsdrewmiller/angular-perfect-scrollbar/blob/master/src/angular-perfect-scrollbar.js#L52)

```
$elem.bind('mouseenter', update('mouseenter'));
```

Please guys, Can you tell me how this line works?

I think it works as unexpected because of:
1. The `update` function returns undefined
2. It invokes only the first time when the file.js get parsed
3. It doesn't invoke every time the mouse enter the element

It should be 

```
$elem.bind('mouseenter', function() {
  update('mouseenter');
});
```

Or the update function should return another function.

Thanks for reading!

**Comment by kxhjp09** [comment]
+1

**Comment by isherwood** [comment]
Fixed in later versions.
