### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by cmacdonnacha** [itsdrewmiller/angular-perfect-scrollbar#78]
Hey,

Just wondering if you plan on pulling in some of the 20 outstanding pull requests as they would fix a lot of the currently open issues?

**Comment by itsdrewmiller** [comment]
Looking for an additional maintainer (see readme) - a lot of people have submitted PRs that don't work at all, and I don't really have time to test everything.

**Comment by cmacdonnacha** [comment]
Ah I see. Unfortunately I don't have time to contribute but hopefully someone will come along to give a hand.
