### ISSUE TITLE
Drop jQuery dependency

### ISSUE THREAD

**Issue by cyril-blanco** [itsdrewmiller/angular-perfect-scrollbar#84]
Currently, your directive relies on jQuery. But the perfect-scrollbar code doesn't need it: your directive could work the same with vanilla JS. It would fix #55 at least.

I had to give up on using this directive because I have no jQuery available in my app. I ended up rolling my own perfect-scrollbar integration, but I still want to use your code. 

PR #47 does the job, you can see how the main script was modified: https://github.com/CareerCruising/angular-perfect-scrollbar/blob/e27ef2b9fa485dce55b591bfefad8e5260f88460/src/angular-perfect-scrollbar.js

**Comment by isherwood** [comment]
I'm looking into this. Safe to say that jQlite (included with AngularJS) would also be acceptable, right?

**Comment by cyril-blanco** [comment]
Yes!Le 24 avr. 2017 10:27 PM, Clint Buhs <notifications@github.com> a écrit :I'm looking into this. Safe to say that jQlite (included with AngularJS) would also be acceptable, right?

**Comment by isherwood** [comment]
Completed with PR94 on version 0.2.0.
