### ISSUE TITLE
Always Visible y-axis

### ISSUE THREAD

**Issue by sureshkoduri** [itsdrewmiller/angular-perfect-scrollbar#87]
Hi, I want scrollbars to be visible always. Please help me how to do this?

**Comment by isherwood** [comment]
You can do so with CSS. Override the opacity values for non-hover states.

**Comment by sureshkoduri** [comment]
Can you give me some code examples(fiddle or bin)?

**Comment by isherwood** [comment]
```
.ps-scrollbar-x-rail, .ps-scrollbar-y-rail {
    opacity: 1;
}
```

You'll want to get familiar with your browser's document inspector to make this kind of thing trivial. :)

**Comment by isherwood** [comment]
An always visible option may be available in a near future release. Please use the CSS above until then.
