### ISSUE TITLE
event not work

### ISSUE THREAD

**Issue by QuietHeartThinkingFar** [itsdrewmiller/angular-perfect-scrollbar#89]
<perfect-scrollbar class="scroller" wheel-propagation="true" wheel-speed="1" min-scrollbar-length="20">
                <div class="role-list-item" ng-repeat="role in allRoles" ng-class="{'selected':role.isSelected}">
                    <div class="item-title" ng-click="changeRole($index)">{{role.job}}</div>
                    <div class="item-after"
                         ng-click="deleteRole($index)">X
                    </div>
                </div>
                <div class="role-add-item" ng-show="showAddRole">
                    <div class="item-title">
                        <input ng-model="newRoleName" ng-blur="submitAddRole()" ng-change="checkInput()" set-Focus>
                    </div>
                </div>
                </perfect-scrollbar>

the ng-blur is not work

**Comment by isherwood** [comment]
Sorry about the late reply. Does ngBlur work on that element when PS isn't implemented? 

Closing until there's further activity.
