### ISSUE TITLE
Not catching mouse leave event when re calculates container's height

### ISSUE THREAD

**Issue by ricardovalquin** [itsdrewmiller/angular-perfect-scrollbar#93]
Hi, I'm facing a weird behavior when the height of the container changes:

I have a search box and when you perform a search, the height of the container changes based on the results and when you clean the search, it goes back to normal then you just move the mouse and the scroll starts acting.
I left a video for this for a better understanding: 
https://youtu.be/QOZx4dpHqWc

**Comment by isherwood** [comment]
Sorry about the slow response. Can you provide a demo, maybe in JSFiddle? 

Closing until there's further activity.
